using System.Text.Json;

namespace Chat.Console.Services;

public static class QuestionRecommendService
{
    public static async Task Recommend(string dbSchema, string userInput, short recommendationCount = 3)
    {
        AiService.ChatHistory.Clear();
        AiService.ChatHistory.AddSystemMessage(SystemPrompt);

        var userPrompt = UserPrompt.Replace("{{$DbSchema}}", dbSchema)
            .Replace("{{UserQuestion}}", userInput)
            .Replace("{{RecommendationCount}}", recommendationCount.ToString());
        
        AiService.ChatHistory.AddUserMessage(userPrompt);
        var jsonResponse = await AiService.AskAi();

        var recommendedQuestions = JsonSerializer.Deserialize<List<string>>(jsonResponse, new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
            AllowTrailingCommas = true
        });

        recommendedQuestions?.ForEach(question =>
        {
            System.Console.WriteLine($"● {question}");
        });
    }

    private const string SystemPrompt =
        """
        You are an expert in data analysis and SQL query generation. 
        Given a data model specification, your task is to generate insightful, 
        specific questions that can be answered using the provided data model and based on the original user's question.

        ## JSON Output Structure

        Output all questions in the following format and do not wrap in code-blocks:
        [
            "<generated question>",
            ...
        ]

        ## Example Output
        [
          "What was the total revenue generated by each region in the last year?",
          "How do customer preferences differ between age groups?",
          "How does the conversion rate vary across different lead sources?",
          "What percentage of contacts have incomplete or missing key properties?"
        ]

        """;

    private const string UserPrompt =
        """
        Database Schema:
        ```sql
        {{$DbSchema}}
        ```

        Generate {{RecommendationCount}} insightful questions. The questions must be related to the user's questions. 
        User's question: {{UserQuestion}}
        """;
}